channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=22.3.1
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.2.0
  - defusedxml==0.7.1
  - lightgbm==3.3.2
  - matplotlib==3.6.2
  - pandas==1.5.2
  - psutil==5.9.4
  - typing-extensions==4.4.0
name: mlflow-env
